spring.application.name=AdminService
server.port=1431

eureka.instance.appname=adminservice
eureka.instance.hostname=localhost

eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

management.info.env.enabled=true
management.endpoints.web.exposure.include=*