spring.application.name=ApiGateway
server.port=1430

eureka.instance.hostname=localhost
eureka.instance.appname=gatewayservice

spring.cloud.gateway.server.webmvc.routes[0].id=AdminService
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:1431
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/admin/**

spring.cloud.gateway.server.webmvc.routes[1].id=UserService-UserAPI
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:1432
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/user-api/**

spring.cloud.gateway.server.webmvc.routes[2].id=UserService-GoalAPI
spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:1432
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/goal-api/**

spring.cloud.gateway.server.webmvc.routes[3].id=UserService-ExpenseAPI
spring.cloud.gateway.server.webmvc.routes[3].uri=http://localhost:1432
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/expense-api/**

spring.cloud.gateway.server.webmvc.routes[4].id=UserService-IncomeAPI
spring.cloud.gateway.server.webmvc.routes[4].uri=http://localhost:1432
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/income-api/**

spring.cloud.gateway.server.webmvc.routes[5].id=UserService-AdminAPI
spring.cloud.gateway.server.webmvc.routes[5].uri=http://localhost:1432
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/admin-api/**



management.info.env.enabled=true
management.endpoints.web.exposure.include=*

